PORT = 22
ADAM = 'adam'
INTERVAL = 3
BATCH_SIZE = '6'
SEED_VALUE = 1337
LOCAL_PATH = '/tmp/'
MODEL_NAME = 'model.h5'
JSON_EXTENSION = '*.json'
EXTENSIONS = ['.png', '.json']
MODEL_JSON_NAME = 'model.json'
DATA_PATH = './resources/data/'
TF_CPP_MIN_LOG_LEVEL_VALUE = '2'
MODEL_PATH = './resources/model/'
DEPTH_PATH = './resources/depth/'
DATASET_PATH = './resources/dataset/'
SKELETON_PATH = './resources/skeleton/'
MODEL_WEIGHTS_NAME = 'model_weights.h5'
TF_CPP_MIN_LOG_LEVEL = 'TF_CPP_MIN_LOG_LEVEL'
HEADERS = {'Content-type': 'application/json'}
